name: gen_flask_pro python2 package
on:
  push:
    branches: [ master ]
    paths:
      - 'gen_flask_pro/**'
      - 'MANIFEST.in'
      - 'pyproject.toml'
      - 'setup.cfg'
      - 'setup.py'
  pull_request:
    branches: [ master ]
    paths:
      - 'gen_flask_pro/**'
      - 'MANIFEST.in'
      - 'pyproject.toml'
      - 'setup.cfg'
      - 'setup.py'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: gen_flask_pro python2 package set up python
      uses: actions/setup-python@v1
      with:
        python-version: '2.x'
    - name: gen_flask_pro python2 package install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel
        pip install -r requirements.txt
    - name: gen_flask_pro python2 package build
      run: |
        python setup.py --github sdist bdist_wheel
